# Generated by Django 5.2.4 on 2025-07-20 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('sex', models.CharField(default=None, max_length=1)),
                ('annual_income', models.IntegerField(default=0)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('mobile', models.IntegerField(default=0)),
                ('occupation', models.CharField(default=None, max_length=50)),
                ('DOB', models.DateField(default=None)),
                ('user_name', models.CharField(default=None, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(default=None, max_length=50)),
                ('recipient_account_number', models.IntegerField()),
                ('transfer_amount', models.IntegerField()),
                ('transfer_method', models.CharField(max_length=20)),
                ('purpose', models.CharField(default='null', max_length=100)),
                ('date_of_transfer', models.DateField(default=datetime.date.today)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(default='Unknown', max_length=100)),
                ('recipient_upi_id', models.CharField(max_length=100)),
                ('payment_amount', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_payment', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='PresentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='India', max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('user_name', models.CharField(default=None, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RecentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default=None, max_length=50)),
                ('sender_account_number', models.IntegerField()),
                ('recipient_name', models.CharField(default=None, max_length=50)),
                ('recipient_account_number', models.IntegerField()),
                ('transfer_amount', models.IntegerField()),
                ('transfer_method', models.CharField(default='IMPS', max_length=20)),
                ('description', models.CharField(default='null', max_length=100)),
                ('date_of_transfer', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('user_name', models.CharField(default=None, max_length=150)),
                ('upi_id', models.CharField(editable=False, max_length=100)),
            ],
        ),
    ]
