# Generated by Django 5.2.4 on 2025-07-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenttransaction',
            name='transfer_method',
            field=models.CharField(max_length=20),
        ),
    ]
