# Generated by Django 5.2.4 on 2025-07-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_recenttransaction_transfer_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='account_number',
            field=models.IntegerField(max_length=18, unique=True),
        ),
    ]
