# Generated by Django 5.2.4 on 2025-07-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_status_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='account_number',
            field=models.IntegerField(unique=True),
        ),
    ]
