# Generated by Django 5.2.4 on 2025-07-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_status_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='debit_card_number',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
