# Generated by Django 5.2.4 on 2025-07-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_status_debit_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='debit_card_number',
        ),
    ]
