# Generated by Django 5.2.4 on 2025-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_status_debit_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=None, max_length=150)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('tier', models.CharField(choices=[('STANDARD', 'Standard'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='STANDARD', max_length=10)),
                ('daily_limit', models.IntegerField(default=50000)),
                ('monthly_limit', models.IntegerField(default=150000)),
                ('is_active', models.BooleanField(default=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
