# Generated by Django 5.2.4 on 2025-07-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_debitcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DebitCard',
        ),
    ]
