# Generated by Django 5.2.4 on 2025-07-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_delete_debitcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('card_type', models.CharField(choices=[('visa_classic', 'Visa Classic'), ('visa_signature', 'Visa Signature'), ('master_select', 'MasterCard Select'), ('master_world', 'MasterCard World'), ('invite_elite', 'Invite Only Elite Card')], max_length=20)),
                ('network', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('invite', 'Invite Only')], max_length=20)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry_date', models.DateField()),
                ('pin', models.CharField(default='0000', max_length=4)),
                ('blocked', models.BooleanField(default=False)),
                ('tap_and_pay', models.BooleanField(default=True)),
                ('international_use', models.BooleanField(default=True)),
                ('atm_use', models.BooleanField(default=True)),
                ('usage_limit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('tier', models.CharField(choices=[('standard', 'Standard'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=10)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry_date', models.DateField()),
                ('pin', models.CharField(default='0000', max_length=4)),
                ('blocked', models.BooleanField(default=False)),
                ('tap_and_pay', models.BooleanField(default=False)),
                ('international_use', models.BooleanField(default=False)),
                ('atm_use', models.BooleanField(default=True)),
                ('usage_limit', models.IntegerField(default=0)),
            ],
        ),
    ]
