# Generated by Django 5.2.4 on 2025-07-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_creditcard_debitcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
        migrations.DeleteModel(
            name='DebitCard',
        ),
    ]
